version: '3'
services:
  app:
    build:
      context: ./nodeApp
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    